apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-jwt
  namespace: nexus-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-aws-secrets
    kind: ClusterSecretStore
  target:
    name: nexus-jwt
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: nexus/staging/jwt
        property: secret