apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-turn
  namespace: nexus-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-aws-secrets
    kind: ClusterSecretStore
  target:
    name: nexus-turn
    creationPolicy: Owner
  data:
    - secretKey: urls
      remoteRef:
        key: nexus/staging/turn
        property: urls
    - secretKey: username
      remoteRef:
        key: nexus/staging/turn
        property: username
    - secretKey: password
      remoteRef:
        key: nexus/staging/turn
        property: password