apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-db
  namespace: nexus-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: nexus-aws-secrets
    kind: ClusterSecretStore
  target:
    name: nexus-db
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: nexus/staging/database
        property: url