apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-staging

resources:
  - namespace.yaml
  - ../external-secrets/cluster-secret-store.yaml
  - external-secret-db.yaml
  - external-secret-jwt.yaml
  - external-secret-turn.yaml
  - ../services/identity-deployment.yaml
  - ../services/content-deployment.yaml
  - ../services/social-graph-deployment.yaml
  - ../services/professional-deployment.yaml
  - ../services/hub-deployment.yaml
  - ../services/commerce-deployment.yaml
  - ../services/collaboration-deployment.yaml
  - ../services/notification-deployment.yaml
  - ../istio/peer-authentication.yaml

images:
  - name: ${ECR_REGISTRY}/nexus-identity
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-content
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-social-graph
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-professional
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-hub
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-commerce
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-collaboration
    newTag: staging
  - name: ${ECR_REGISTRY}/nexus-notification
    newTag: staging

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /metadata/namespace
        value: nexus-staging