"use client";

import {
  Activity,
  AtSign,
  BarChart3,
  Bell,
  Briefcase,
  CalendarDays,
  Camera,
  CircleDot,
  Cloud,
  Coins,
  Contact,
  CreditCard,
  Crosshair,
  Download,
  Eye,
  FileText,
  Gift,
  Globe,
  HandCoins,
  HelpCircle,
  Inbox,
  Landmark,
  LayoutGrid,
  Link2,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Minus,
  Network,
  Phone,
  Plus,
  QrCode,
  Radio,
  Receipt,
  RotateCcw,
  Rss,
  ScanSearch,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Target,
  Upload,
  UserCircle2,
  Users,
  Video,
  Wallet,
  Wifi,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/cn";

export const APP_ICONS = {
  feed: LayoutGrid,
  twin: UserCircle2,
  studio: Video,
  live: Radio,
  status: Activity,
  calls: Phone,
  teams: Users,
  contacts: Contact,
  hub: Globe,
  market: ShoppingBag,
  map: MapPin,
  find: Crosshair,
  connect: Network,
  inbox: Inbox,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  satellite: ScanSearch,
  prefs: Settings,
  mail: Inbox,
  help: HelpCircle,
  privacy: Shield,
  eye: Eye,
  chart: BarChart3,
  friends: Users,
  followers: Link2,
  groups: Users,
  location: MapPin,
  sos: Bell,
  finder: Crosshair,
  share: Share2,
  network: Network,
  viewers: Eye,
  impressions: BarChart3,
  connectors: Link2,
  slack: Briefcase,
  github: Link2,
  linkedin: Link2,
  email: AtSign,
  social: Rss,
  schedule: CalendarDays,
  podcast: Mic,
  vlog: Camera,
  streams: CircleDot,
  upload: Upload,
  download: Download,
  wallet: Wallet,
  addCard: Plus,
  stripe: CreditCard,
  paypal: Wallet,
  receipt: Receipt,
  refund: RotateCcw,
  crypto: Coins,
  rewards: Gift,
  promotions: Sparkles,
  bonus: Coins,
  star: Star,
  marketplace: Store,
  sell: Store,
  shop: ShoppingCart,
  cart: ShoppingCart,
  qr: QrCode,
  sales: HandCoins,
  jobs: Briefcase,
  hiring: FileText,
  marketing: Megaphone,
  campaigns: Target,
  analytics: BarChart3,
  monetization: Landmark,
  tax: FileText,
  minus: Minus,
  wifi: Wifi,
  airdrop: Share2,
  cloud: Cloud,
  terms: FileText,
  legal: Shield,
  agreements: FileText,
  findMe: Bell,
  memberMap: MapPin,
  loginLocation: ScanSearch,
  voice: Mic,
  ai: Sparkles,
  ephemeral: CircleDot,
  stats: BarChart3,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

interface AppIconProps {
  name: AppIconName;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function AppIcon({
  name,
  size = 16,
  className,
  strokeWidth = 1.75,
}: AppIconProps) {
  const Icon = APP_ICONS[name];
  if (!Icon) return null;
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={cn("shrink-0", className)}
      aria-hidden
    />
  );
}

/** Resolve legacy emoji or icon id strings to AppIconName */
export function resolveIconName(raw?: string): AppIconName | null {
  if (!raw) return null;
  if (raw in APP_ICONS) return raw as AppIconName;
  const LEGACY: Record<string, AppIconName> = {
    "◈": "feed",
    "◎": "twin",
    "▣": "studio",
    "●": "live",
    "◌": "status",
    "☎": "calls",
    "▤": "teams",
    "☰": "contacts",
    "◉": "hub",
    "🛒": "market",
    "⌖": "map",
    "⊕": "find",
    "◇": "connect",
    "✉": "inbox",
    "⚙": "settings",
    "🔐": "shield",
    "📱": "smartphone",
    "🛰": "satellite",
    "💬": "help",
    "🛡": "privacy",
    "👁": "eye",
    "📊": "stats",
    "👥": "friends",
    "↔": "followers",
    "📍": "location",
    "🆘": "sos",
    "↗": "share",
    "👀": "viewers",
    "📈": "impressions",
    "🔗": "connectors",
    "💼": "slack",
    "🗓": "schedule",
    "🎙": "podcast",
    "📹": "vlog",
    "⬆": "upload",
    "⬇": "download",
    "💳": "wallet",
    "＋": "addCard",
    "🧾": "receipt",
    "↩": "refund",
    "🎁": "rewards",
    "✨": "promotions",
    "🪙": "bonus",
    "★": "star",
    "🛍": "marketplace",
    "🏪": "sell",
    "📅": "schedule",
    "💰": "sales",
    "📋": "hiring",
    "📣": "marketing",
    "🎯": "campaigns",
    "💎": "monetization",
    "📑": "tax",
    "−": "minus",
    "📶": "wifi",
    "📡": "airdrop",
    "☁": "cloud",
    "📜": "terms",
    "🔒": "legal",
    "✍": "agreements",
    "🎤": "voice",
    "✦": "ai",
  };
  return LEGACY[raw] ?? null;
}